using System.Collections.Generic;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public sealed partial class GameHud : Control
{
    public void SetNames(List<string> playerNames)
    {
        LabelPlayerOneName.Text = playerNames[0];
        LabelPlayerTwoName.Text = playerNames[1];
    }

    public void SetScore(List<int> scores)
    {
        LabelPlayerOneScore.Text = scores[0].ToString();
        LabelPlayerTwoScore.Text = scores[1].ToString();
    }
}