using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public sealed partial class InputPrompt : Control
{
    public string? Text
    {
        get => Prompt.Text;
        set => Prompt.Text = value;
    }
    
    public string? Placeholder
    {
        get => Input.PlaceHolder;
        set => Input.PlaceHolder = value;
    }
}