using System.Collections.Generic;
using Content.Shared;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public sealed partial class LobbyListHud : Control
{
    public LobbyListHud()
    {
        RobustXamlLoader.Load(this);
        PasswordPrompt.CancelButton.OnPressed += TogglePasswordPrompt;
        
#if DEBUG
        CreateLobbyName.Text = "TestLobby";
#endif
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        //this should never happen, but just in case
        if(!LobbyListPanel.Visible)
            TogglePasswordPrompt();
    }

    private string lobbyId;
    private BeachballSystem _system;
    void OnLobbyListOnOnItemSelected(ItemList.ItemListSelectedEventArgs x)
    {
        lobbyId = x.ItemList[x.ItemIndex].Text!;
        if(!_system.Lobbies.TryFirstOrDefault(x => x.Name == lobbyId, out var lobby))
            return;

        if (lobby.Password)
        {
            TogglePasswordPrompt();
        }
        else
        {
            _system.JoinLobby(lobbyId);
        }
    }
    
    void OnCreateLobbyOnOnPressed(BaseButton.ButtonEventArgs x) => _system.CreateLobby(CreateLobbyName.Text);
    void OnBackButtonPressed(BaseButton.ButtonEventArgs x) => _system.Disconnect();

    void OnEnterWithPasswordPressed(BaseButton.ButtonEventArgs x)
    {
        _system.JoinLobby(lobbyId, PasswordPrompt.Input.Text!);
        TogglePasswordPrompt();
    }

    void TogglePasswordPrompt(BaseButton.ButtonEventArgs? x = null)
    {
        PasswordPrompt.Visible = !PasswordPrompt.Visible;
        LobbyListPanel.Visible = !LobbyListPanel.Visible;
        if (!PasswordPrompt.Visible)
            PasswordPrompt.Input.Text = string.Empty;
    }
    
    public void SubscribeToEvents(BeachballSystem system)
    {
        _system = system;

        LobbyList.OnItemSelected += OnLobbyListOnOnItemSelected;
        CreateLobby.OnPressed += OnCreateLobbyOnOnPressed;
        PasswordPrompt.ConfirmButton.OnPressed += OnEnterWithPasswordPressed;
        BackButton.OnPressed += OnBackButtonPressed;
    }
    
    public void UnsubscribeFromEvents()
    {
        _system = null;

        LobbyList.OnItemSelected -= OnLobbyListOnOnItemSelected;
        CreateLobby.OnPressed -= OnCreateLobbyOnOnPressed;
        PasswordPrompt.ConfirmButton.OnPressed -= OnEnterWithPasswordPressed;
        BackButton.OnPressed -= OnBackButtonPressed;
    }
    
    public void UpdateLobbyList(BeachballSystem system)
    {
        LobbyList.Clear();
        foreach (var lobby in system.Lobbies)
        {
            LobbyList.AddItem(lobby.Name);
        }
    }
}