using System.Collections.Generic;
using Content.Shared;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.UserInterface.Hud;

[GenerateTypedNameReferences]
public sealed partial class LobbyListHud : Control
{
    private BeachballSystem _system;
    void OnLobbyListOnOnItemSelected(ItemList.ItemListSelectedEventArgs x) => _system.JoinLobby(x.ItemList[x.ItemIndex].Text!);
    void OnCreateLobbyOnOnPressed(BaseButton.ButtonEventArgs x) => _system.CreateLobby(CreateLobbyName.Text);
    void OnBackButtonPressed(BaseButton.ButtonEventArgs x) => _system.Disconnect();

    public void SubscribeToEvents(BeachballSystem system)
    {
        _system = system;

        LobbyList.OnItemSelected += OnLobbyListOnOnItemSelected;
        CreateLobby.OnPressed += OnCreateLobbyOnOnPressed;
        BackButton.OnPressed += OnBackButtonPressed;
    }
    
    public void UnsubscribeFromEvents()
    {
        _system = null;

        LobbyList.OnItemSelected -= OnLobbyListOnOnItemSelected;
        CreateLobby.OnPressed -= OnCreateLobbyOnOnPressed;
        BackButton.OnPressed -= OnBackButtonPressed;
    }
    
    public void UpdateLobbyList(BeachballSystem system)
    {
        LobbyList.Clear();
        foreach (var lobby in system.Lobbies)
        {
            LobbyList.AddItem(lobby.Name);
        }
    }
}